architecture: violation_weighted_edge_network_v2
model_file: models/architectures/model9/model9

hidden_dim: 128
edge_depth: 3
norm: layer
activation: GELU
max_displacement: 0.0912   # 1.2 * rd=0.0760
