architecture: self_attention_mlp
output: displacement  # options: displacement, corrected_positions

hidden_dim: 128
num_attention_modules: 8
batch_norm: true
activation: ELU  # options: ELU, ReLU, LeakyReLU, GELU
